"""Prompt templates package."""

from lexicon.shared.prompts.contract_review import (
    ANALYZE_RISK_PROMPT,
    DETECT_UNUSUAL_CLAUSES_PROMPT,
    EXTRACT_CLAUSES_PROMPT,
    EXTRACT_CONTRACT_METADATA_PROMPT,
    EXTRACT_OBLIGATIONS_PROMPT,
)
from lexicon.shared.prompts.document_analysis import (
    CLASSIFY_DOCUMENT_PROMPT,
    EXTRACT_KEY_POINTS_PROMPT,
    EXTRACT_PARTIES_PROMPT,
    SUMMARIZE_DOCUMENT_PROMPT,
)
from lexicon.shared.prompts.legal_research import (
    ASSESS_RELEVANCE_PROMPT,
    EXTRACT_CITATIONS_PROMPT,
    RESEARCH_QUERY_PROMPT,
    SYNTHESIZE_ANSWER_PROMPT,
)

__all__ = [
    "ANALYZE_RISK_PROMPT",
    "ASSESS_RELEVANCE_PROMPT",
    "CLASSIFY_DOCUMENT_PROMPT",
    "DETECT_UNUSUAL_CLAUSES_PROMPT",
    "EXTRACT_CITATIONS_PROMPT",
    "EXTRACT_CLAUSES_PROMPT",
    "EXTRACT_CONTRACT_METADATA_PROMPT",
    "EXTRACT_KEY_POINTS_PROMPT",
    "EXTRACT_OBLIGATIONS_PROMPT",
    "EXTRACT_PARTIES_PROMPT",
    "RESEARCH_QUERY_PROMPT",
    "SUMMARIZE_DOCUMENT_PROMPT",
    "SYNTHESIZE_ANSWER_PROMPT",
]